version: 0.2

phases:
  build:
    commands:
      - pip install --upgrade awscli
      - npm install --prefix skill/
      - npm test --prefix skill/
      - npm run build --prefix skill/
      - npm install --prefix voice-interface/
      - npm run start --prefix voice-interface/
      - mv voice-interface/models/*.json interactionModel/
      - aws cloudformation package --template-file cfn.yaml --s3-bucket ${ARTIFACTS_BUCKET} --output-template-file cfn.packaged.yaml

artifacts:
  files:
    - cfn.packaged.yaml
    - interactionModel/*.json
    - skill.json