AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PSE Alexa Skill
Resources:
  SkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bundle.handler
      Runtime: nodejs8.10
      Timeout: 10
      AutoPublishAlias: latest
      CodeUri: ./skill/dist/bundle.js
  SkillFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref SkillFunction.Version
      Principal: alexa-appkit.amazon.com

Outputs:
  overrides:
    Value: !Sub |-
      {
        "manifest": {
          "apis": {
            "custom": {
              "endpoint": {
                "uri": "${SkillFunction.Version}"
              }
            }
          }
        }
      }