AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PSE Alexa Skill
Resources:
  AssetBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::AccountId}-${AWS::StackName}-${AWS::Region}-assets'
  AssetBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref AssetBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${AssetBucket}/*
            Principal: '*'
  SkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bundle.handler
      Runtime: nodejs8.10
      Timeout: 10
      AutoPublishAlias: latest
      CodeUri: ./skill/dist/bundle.js
  SkillFunctionPermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref SkillFunction.Version
      Principal: alexa-appkit.amazon.com

Outputs:
  overrides:
    Value: !Sub |-
      {
        "manifest": {
          "apis": {
            "custom": {
              "endpoint": {
                "uri": "${SkillFunction.Version}"
              }
            }
          }
        }
      }