/*
 * Copyright (c) 2018. Taimos GmbH http://www.taimos.de
 */

export interface Element {
  'number' : number;
  'name' : string;
  'symbol' : string;
  'mass' : number;
  'neutrons' : number | string;
  'negativity' : number | string;
  'outerElectrons' : number | string;
  'electronConfig' : string;
  'groupNumber' : number | string;
  'phase' : string;
  'firstIonizationEnergy' : number | string;
  'halflife' : number | string;
  'meltingPoint' : number | string;
  'boilingPoint' : number | string;
  'sublimationPoint' : number | string;
  'density20' : number | string;
  'density0' : number | string;
}

export const data : { [key : number] : Element } = {
  1: {
    number: 1,
    name: 'Wasserstoff',
    symbol: 'H',
    mass: 1,
    neutrons: 0,
    negativity: 2.2,
    outerElectrons: 1,
    electronConfig: '1s^1',
    groupNumber: 1,
    phase: 'gas',
    firstIonizationEnergy: 1312,
    halflife: 0,
    meltingPoint: -259.14,
    boilingPoint: -252,
    sublimationPoint: '',
    density20: '',
    density0: 0.09,
  },
  2: {
    number: 2,
    name: 'Helium',
    symbol: 'He',
    mass: 4,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '1s^2',
    groupNumber: 18,
    phase: 'gas',
    firstIonizationEnergy: 2372.3,
    halflife: '',
    meltingPoint: '−272.2',
    boilingPoint: '−269',
    sublimationPoint: '',
    density20: '',
    density0: 0.179,
  },
  3: {
    number: 3,
    name: 'Lithium',
    symbol: 'Li',
    mass: 6.94,
    neutrons: '',
    negativity: 0.98,
    outerElectrons: 1,
    electronConfig: '2s^1',
    groupNumber: 1,
    phase: 'solid',
    firstIonizationEnergy: 520.2,
    halflife: '',
    meltingPoint: 180.54,
    boilingPoint: 1330,
    sublimationPoint: '',
    density20: 0.534,
    density0: '',
  },
  4: {
    number: 4,
    name: 'Beryllium',
    symbol: 'Be',
    mass: 9.01,
    neutrons: '',
    negativity: 1.57,
    outerElectrons: 2,
    electronConfig: '2s^2',
    groupNumber: 2,
    phase: 'solid',
    firstIonizationEnergy: 899.5,
    halflife: '',
    meltingPoint: 1287,
    boilingPoint: 2969,
    sublimationPoint: '',
    density20: 1.848,
    density0: '',
  },
  5: {
    number: 5,
    name: 'Bor',
    symbol: 'B',
    mass: 10.81,
    neutrons: '',
    negativity: 2.04,
    outerElectrons: 3,
    electronConfig: '2s^2 2p^1',
    groupNumber: 13,
    phase: 'solid',
    firstIonizationEnergy: 800.6,
    halflife: '',
    meltingPoint: 2076,
    boilingPoint: 3930,
    sublimationPoint: '',
    density20: 2.46,
    density0: '',
  },
  6: {
    number: 6,
    name: 'Kohlenstoff',
    symbol: 'C',
    mass: 12.01,
    neutrons: '',
    negativity: 2.55,
    outerElectrons: 4,
    electronConfig: '2s^2 2p^2',
    groupNumber: 14,
    phase: 'solid',
    firstIonizationEnergy: 1086.5,
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: 3642,
    density20: 'Graphit: 2.26, Diamant: 3.51',
    density0: '',
  },
  7: {
    number: 7,
    name: 'Stickstoff',
    symbol: 'N',
    mass: 14.01,
    neutrons: '',
    negativity: 3.04,
    outerElectrons: 5,
    electronConfig: '2s^2 2p^3',
    groupNumber: 15,
    phase: 'gas',
    firstIonizationEnergy: 1402.3,
    halflife: '',
    meltingPoint: '−210.1',
    boilingPoint: '−196',
    sublimationPoint: '',
    density20: '',
    density0: 1.25,
  },
  8: {
    number: 8,
    name: 'Sauerstoff',
    symbol: 'O',
    mass: 16,
    neutrons: '',
    negativity: 3.44,
    outerElectrons: 6,
    electronConfig: '2s^2 2p^4',
    groupNumber: 16,
    phase: 'gas',
    firstIonizationEnergy: 1313.9,
    halflife: '',
    meltingPoint: '−218.3',
    boilingPoint: '−183',
    sublimationPoint: '',
    density20: '',
    density0: 1.429,
  },
  9: {
    number: 9,
    name: 'Fluor',
    symbol: 'F',
    mass: 19,
    neutrons: '',
    negativity: 4,
    outerElectrons: 7,
    electronConfig: '2s^2 2p^5',
    groupNumber: 17,
    phase: 'gas',
    firstIonizationEnergy: 1681,
    halflife: '',
    meltingPoint: '−219.62',
    boilingPoint: '−188',
    sublimationPoint: '',
    density20: '',
    density0: 1.697,
  },
  10: {
    number: 10,
    name: 'Neon',
    symbol: 'Ne',
    mass: 20.18,
    neutrons: '',
    negativity: '',
    outerElectrons: 8,
    electronConfig: '2s^2 2p^6',
    groupNumber: 18,
    phase: 'gas',
    firstIonizationEnergy: 2080.7,
    halflife: '',
    meltingPoint: '−248.59',
    boilingPoint: '−246',
    sublimationPoint: '',
    density20: '',
    density0: 0.9,
  },
  11: {
    number: 11,
    name: 'Natrium',
    symbol: 'Na',
    mass: 22.99,
    neutrons: '',
    negativity: 0.93,
    outerElectrons: 1,
    electronConfig: '3s^1',
    groupNumber: 1,
    phase: 'solid',
    firstIonizationEnergy: 495.8,
    halflife: '',
    meltingPoint: 97.72,
    boilingPoint: 890,
    sublimationPoint: '',
    density20: 0.968,
    density0: '',
  },
  12: {
    number: 12,
    name: 'Magnesium',
    symbol: 'Mg',
    mass: 24.31,
    neutrons: '',
    negativity: 1.31,
    outerElectrons: 2,
    electronConfig: '3s^2',
    groupNumber: 2,
    phase: 'solid',
    firstIonizationEnergy: 737.7,
    halflife: '',
    meltingPoint: 650,
    boilingPoint: 1110,
    sublimationPoint: '',
    density20: 1.738,
    density0: '',
  },
  13: {
    number: 13,
    name: 'Aluminium',
    symbol: 'Al',
    mass: 26.98,
    neutrons: '',
    negativity: 1.61,
    outerElectrons: 3,
    electronConfig: '3s^2 3p^1',
    groupNumber: 13,
    phase: 'solid',
    firstIonizationEnergy: 577.5,
    halflife: '',
    meltingPoint: 660.2,
    boilingPoint: 2470,
    sublimationPoint: '',
    density20: 2.699,
    density0: '',
  },
  14: {
    number: 14,
    name: 'Silicium',
    symbol: 'Si',
    mass: 28.09,
    neutrons: '',
    negativity: 1.9,
    outerElectrons: 4,
    electronConfig: '3s^2 3p^2',
    groupNumber: 14,
    phase: 'solid',
    firstIonizationEnergy: 786.5,
    halflife: '',
    meltingPoint: 1410,
    boilingPoint: 3260,
    sublimationPoint: '',
    density20: 2.336,
    density0: '',
  },
  15: {
    number: 15,
    name: 'Phosphor',
    symbol: 'P',
    mass: 30.97,
    neutrons: '',
    negativity: 2.19,
    outerElectrons: 5,
    electronConfig: '3s^2 3p^3',
    groupNumber: 15,
    phase: 'solid',
    firstIonizationEnergy: 1011.8,
    halflife: '',
    meltingPoint: 44.2,
    boilingPoint: 280,
    sublimationPoint: '',
    density20: 'weiß: 1.83, rot: 2.0...2.4, schwarz: 2.69',
    density0: '',
  },
  16: {
    number: 16,
    name: 'Schwefel',
    symbol: 'S',
    mass: 32.06,
    neutrons: '',
    negativity: 2.58,
    outerElectrons: 6,
    electronConfig: '3s^2 3p^4',
    groupNumber: 16,
    phase: 'solid',
    firstIonizationEnergy: 999.6,
    halflife: '',
    meltingPoint: 115.21,
    boilingPoint: 445,
    sublimationPoint: '',
    density20: 2.07,
    density0: '',
  },
  17: {
    number: 17,
    name: 'Chlor',
    symbol: 'Cl',
    mass: 35.45,
    neutrons: '',
    negativity: 3.16,
    outerElectrons: 7,
    electronConfig: '3s^2 3p^5',
    groupNumber: 17,
    phase: 'gas',
    firstIonizationEnergy: 1251.2,
    halflife: '',
    meltingPoint: '−101.5',
    boilingPoint: '−34.6',
    sublimationPoint: '',
    density20: '',
    density0: 3.215,
  },
  18: {
    number: 18,
    name: 'Argon',
    symbol: 'Ar',
    mass: 39.95,
    neutrons: '',
    negativity: '',
    outerElectrons: 8,
    electronConfig: '3s^2 3p^6',
    groupNumber: 18,
    phase: 'gas',
    firstIonizationEnergy: 1520.8,
    halflife: '',
    meltingPoint: '−189.3',
    boilingPoint: '−186',
    sublimationPoint: '',
    density20: '',
    density0: 1.784,
  },
  19: {
    number: 19,
    name: 'Kalium',
    symbol: 'K',
    mass: 39.1,
    neutrons: '',
    negativity: 0.82,
    outerElectrons: 1,
    electronConfig: '4s^1',
    groupNumber: 1,
    phase: 'solid',
    firstIonizationEnergy: 418.8,
    halflife: '',
    meltingPoint: 63.38,
    boilingPoint: 774,
    sublimationPoint: '',
    density20: 0.856,
    density0: '',
  },
  20: {
    number: 20,
    name: 'Calcium',
    symbol: 'Ca',
    mass: 40.08,
    neutrons: '',
    negativity: 1,
    outerElectrons: 2,
    electronConfig: '4s^2',
    groupNumber: 2,
    phase: 'solid',
    firstIonizationEnergy: 589.8,
    halflife: '',
    meltingPoint: 842,
    boilingPoint: 1487,
    sublimationPoint: '',
    density20: 1.55,
    density0: '',
  },
  21: {
    number: 21,
    name: 'Scandium',
    symbol: 'Sc',
    mass: 44.96,
    neutrons: '',
    negativity: 1.36,
    outerElectrons: 3,
    electronConfig: '3d^1 4s^2',
    groupNumber: 3,
    phase: 'solid',
    firstIonizationEnergy: 633.1,
    halflife: '',
    meltingPoint: 1541,
    boilingPoint: 2730,
    sublimationPoint: '',
    density20: 2.985,
    density0: '',
  },
  22: {
    number: 22,
    name: 'Titan',
    symbol: 'Ti',
    mass: 47.87,
    neutrons: '',
    negativity: 1.54,
    outerElectrons: 4,
    electronConfig: '3d^2 4s^2',
    groupNumber: 4,
    phase: 'solid',
    firstIonizationEnergy: 658.8,
    halflife: '',
    meltingPoint: 1668,
    boilingPoint: 3260,
    sublimationPoint: '',
    density20: 4.5,
    density0: '',
  },
  23: {
    number: 23,
    name: 'Vanadium',
    symbol: 'V',
    mass: 50.94,
    neutrons: '',
    negativity: 1.63,
    outerElectrons: 5,
    electronConfig: '3d^3 4s^2',
    groupNumber: 5,
    phase: 'solid',
    firstIonizationEnergy: 650.9,
    halflife: '',
    meltingPoint: 1910,
    boilingPoint: 3407,
    sublimationPoint: '',
    density20: 6.11,
    density0: '',
  },
  24: {
    number: 24,
    name: 'Chrom',
    symbol: 'Cr',
    mass: 52,
    neutrons: '',
    negativity: 1.66,
    outerElectrons: 6,
    electronConfig: '3d^5 4s^1',
    groupNumber: 6,
    phase: 'solid',
    firstIonizationEnergy: 652.9,
    halflife: '',
    meltingPoint: 1907,
    boilingPoint: 2482,
    sublimationPoint: '',
    density20: 7.14,
    density0: '',
  },
  25: {
    number: 25,
    name: 'Mangan',
    symbol: 'Mn',
    mass: 54.94,
    neutrons: '',
    negativity: 1.55,
    outerElectrons: 7,
    electronConfig: '3d^5 4s^2',
    groupNumber: 7,
    phase: 'solid',
    firstIonizationEnergy: 717.3,
    halflife: '',
    meltingPoint: 1246,
    boilingPoint: 2100,
    sublimationPoint: '',
    density20: 7.43,
    density0: '',
  },
  26: {
    number: 26,
    name: 'Eisen',
    symbol: 'Fe',
    mass: 55.85,
    neutrons: '',
    negativity: 1.83,
    outerElectrons: 8,
    electronConfig: '3d^6 4s^2',
    groupNumber: 8,
    phase: 'solid',
    firstIonizationEnergy: 762.5,
    halflife: '',
    meltingPoint: 1538,
    boilingPoint: 3000,
    sublimationPoint: '',
    density20: 7.874,
    density0: '',
  },
  27: {
    number: 27,
    name: 'Cobalt',
    symbol: 'Co',
    mass: 58.93,
    neutrons: '',
    negativity: 1.88,
    outerElectrons: 9,
    electronConfig: '3d^7 4s^2',
    groupNumber: 9,
    phase: 'solid',
    firstIonizationEnergy: 760.4,
    halflife: '',
    meltingPoint: 1495,
    boilingPoint: 2900,
    sublimationPoint: '',
    density20: 8.9,
    density0: '',
  },
  28: {
    number: 28,
    name: 'Nickel',
    symbol: 'Ni',
    mass: 58.69,
    neutrons: '',
    negativity: 1.91,
    outerElectrons: 10,
    electronConfig: '3d^8 4s^2',
    groupNumber: 10,
    phase: 'solid',
    firstIonizationEnergy: 737.1,
    halflife: '',
    meltingPoint: 1455,
    boilingPoint: 2730,
    sublimationPoint: '',
    density20: 8.908,
    density0: '',
  },
  29: {
    number: 29,
    name: 'Kupfer',
    symbol: 'Cu',
    mass: 63.55,
    neutrons: '',
    negativity: 1.9,
    outerElectrons: 11,
    electronConfig: '3d^10 4s^1',
    groupNumber: 11,
    phase: 'solid',
    firstIonizationEnergy: 745.5,
    halflife: '',
    meltingPoint: 1084.62,
    boilingPoint: 2595,
    sublimationPoint: '',
    density20: 8.92,
    density0: '',
  },
  30: {
    number: 30,
    name: 'Zink',
    symbol: 'Zn',
    mass: 65.38,
    neutrons: '',
    negativity: 1.65,
    outerElectrons: 12,
    electronConfig: '3d^10 4s^2',
    groupNumber: 12,
    phase: 'solid',
    firstIonizationEnergy: 906.4,
    halflife: '',
    meltingPoint: 419.53,
    boilingPoint: 907,
    sublimationPoint: '',
    density20: 7.14,
    density0: '',
  },
  31: {
    number: 31,
    name: 'Gallium',
    symbol: 'Ga',
    mass: 69.72,
    neutrons: '',
    negativity: 1.81,
    outerElectrons: 3,
    electronConfig: '3d^10 4s^2 4p^1',
    groupNumber: 13,
    phase: 'solid',
    firstIonizationEnergy: 578.8,
    halflife: '',
    meltingPoint: 29.76,
    boilingPoint: 2400,
    sublimationPoint: '',
    density20: 5.904,
    density0: '',
  },
  32: {
    number: 32,
    name: 'Germanium',
    symbol: 'Ge',
    mass: 72.63,
    neutrons: '',
    negativity: 2.01,
    outerElectrons: 4,
    electronConfig: '3d^10 4s^2 4p^2',
    groupNumber: 14,
    phase: 'solid',
    firstIonizationEnergy: 762,
    halflife: '',
    meltingPoint: 938.3,
    boilingPoint: 2830,
    sublimationPoint: '',
    density20: 5.323,
    density0: '',
  },
  33: {
    number: 33,
    name: 'Arsen',
    symbol: 'As',
    mass: 74.92,
    neutrons: '',
    negativity: 2.18,
    outerElectrons: 5,
    electronConfig: '3d^10 4s^2 4p^3',
    groupNumber: 15,
    phase: 'solid',
    firstIonizationEnergy: 947,
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: 613,
    density20: 'grau: 5.72, gelb: 1.97, schwarz: 4.7–5.1',
    density0: '',
  },
  34: {
    number: 34,
    name: 'Selen',
    symbol: 'Se',
    mass: 78.97,
    neutrons: '',
    negativity: 2.55,
    outerElectrons: 6,
    electronConfig: '3d^10 4s^2 4p^4',
    groupNumber: 16,
    phase: 'solid',
    firstIonizationEnergy: 941,
    halflife: '',
    meltingPoint: 221,
    boilingPoint: 685,
    sublimationPoint: '',
    density20: 'schwarzes Se bei 60 °C: 4.28, graues Se bei 25 °C: 4.819, rotes Se bei 25 °C: 4.48',
    density0: '',
  },
  35: {
    number: 35,
    name: 'Brom',
    symbol: 'Br',
    mass: 79.9,
    neutrons: '',
    negativity: 2.96,
    outerElectrons: 7,
    electronConfig: '3d^10 4s^2 4p^5',
    groupNumber: 17,
    phase: 'liquid',
    firstIonizationEnergy: 1139.9,
    halflife: '',
    meltingPoint: '−7.3',
    boilingPoint: 58.5,
    sublimationPoint: '',
    density20: '3.12 bei 300K',
    density0: '',
  },
  36: {
    number: 36,
    name: 'Krypton',
    symbol: 'Kr',
    mass: 83.8,
    neutrons: '',
    negativity: 3,
    outerElectrons: 8,
    electronConfig: '3d^10 4s^2 4p^6',
    groupNumber: 18,
    phase: 'gas',
    firstIonizationEnergy: 1350.8,
    halflife: '',
    meltingPoint: '−157.36',
    boilingPoint: '−152',
    sublimationPoint: '',
    density20: '',
    density0: 3.749,
  },
  37: {
    number: 37,
    name: 'Rubidium',
    symbol: 'Rb',
    mass: 85.47,
    neutrons: '',
    negativity: 0.82,
    outerElectrons: 1,
    electronConfig: '5s^1',
    groupNumber: 1,
    phase: 'solid',
    firstIonizationEnergy: 403,
    halflife: '',
    meltingPoint: 39.31,
    boilingPoint: 688,
    sublimationPoint: '',
    density20: 1.532,
    density0: '',
  },
  38: {
    number: 38,
    name: 'Strontium',
    symbol: 'Sr',
    mass: 87.62,
    neutrons: '',
    negativity: 0.95,
    outerElectrons: 2,
    electronConfig: '5s^2',
    groupNumber: 2,
    phase: 'solid',
    firstIonizationEnergy: 549.5,
    halflife: '',
    meltingPoint: 777,
    boilingPoint: 1380,
    sublimationPoint: '',
    density20: 2.63,
    density0: '',
  },
  39: {
    number: 39,
    name: 'Yttrium',
    symbol: 'Y',
    mass: 88.91,
    neutrons: '',
    negativity: 1.22,
    outerElectrons: 3,
    electronConfig: '4d^1 5s^2',
    groupNumber: 3,
    phase: 'solid',
    firstIonizationEnergy: 600,
    halflife: '',
    meltingPoint: 1526,
    boilingPoint: 2930,
    sublimationPoint: '',
    density20: 4.472,
    density0: '',
  },
  40: {
    number: 40,
    name: 'Zirconium',
    symbol: 'Zr',
    mass: 91.22,
    neutrons: '',
    negativity: 1.33,
    outerElectrons: 4,
    electronConfig: '4d^2 5s^2',
    groupNumber: 4,
    phase: 'solid',
    firstIonizationEnergy: 640.1,
    halflife: '',
    meltingPoint: 1857,
    boilingPoint: 4377,
    sublimationPoint: '',
    density20: '6.501 bei 25°C',
    density0: '',
  },
  41: {
    number: 41,
    name: 'Niob',
    symbol: 'Nb',
    mass: 92.91,
    neutrons: '',
    negativity: 1.6,
    outerElectrons: 5,
    electronConfig: '4d^4 5s^1',
    groupNumber: 5,
    phase: 'solid',
    firstIonizationEnergy: 652.1,
    halflife: '',
    meltingPoint: 2477,
    boilingPoint: 4744,
    sublimationPoint: '',
    density20: 8.57,
    density0: '',
  },
  42: {
    number: 42,
    name: 'Molybdän',
    symbol: 'Mo',
    mass: 95.95,
    neutrons: '',
    negativity: 2.16,
    outerElectrons: 6,
    electronConfig: '4d^5 5s^1',
    groupNumber: 6,
    phase: 'solid',
    firstIonizationEnergy: 684.3,
    halflife: '',
    meltingPoint: 2623,
    boilingPoint: 4612,
    sublimationPoint: '',
    density20: 10.28,
    density0: '',
  },
  43: {
    number: 43,
    name: 'Technetium',
    symbol: 'Tc',
    mass: 98.91,
    neutrons: '',
    negativity: 1.9,
    outerElectrons: 7,
    electronConfig: '4d^5 5s^2',
    groupNumber: 7,
    phase: 'solid',
    firstIonizationEnergy: 702,
    halflife: '',
    meltingPoint: 2157,
    boilingPoint: 4265,
    sublimationPoint: '',
    density20: '11.5 bei 25°C',
    density0: '',
  },
  44: {
    number: 44,
    name: 'Ruthenium',
    symbol: 'Ru',
    mass: 101.07,
    neutrons: '',
    negativity: 2.2,
    outerElectrons: 8,
    electronConfig: '4d^7 5s^1',
    groupNumber: 8,
    phase: 'solid',
    firstIonizationEnergy: 710.2,
    halflife: '',
    meltingPoint: 2334,
    boilingPoint: 4150,
    sublimationPoint: '',
    density20: 12.37,
    density0: '',
  },
  45: {
    number: 45,
    name: 'Rhodium',
    symbol: 'Rh',
    mass: 102.91,
    neutrons: '',
    negativity: 2.28,
    outerElectrons: 9,
    electronConfig: '4d^8 5s^1',
    groupNumber: 9,
    phase: 'solid',
    firstIonizationEnergy: 719.7,
    halflife: '',
    meltingPoint: 1964,
    boilingPoint: 3727,
    sublimationPoint: '',
    density20: 12.38,
    density0: '',
  },
  46: {
    number: 46,
    name: 'Palladium',
    symbol: 'Pd',
    mass: 106.42,
    neutrons: '',
    negativity: 2.2,
    outerElectrons: 10,
    electronConfig: '4d^10 5s^0',
    groupNumber: 10,
    phase: 'solid',
    firstIonizationEnergy: 804.4,
    halflife: '',
    meltingPoint: 1554.9,
    boilingPoint: 2960,
    sublimationPoint: '',
    density20: 11.99,
    density0: '',
  },
  47: {
    number: 47,
    name: 'Silber',
    symbol: 'Ag',
    mass: 107.87,
    neutrons: '',
    negativity: 1.93,
    outerElectrons: 11,
    electronConfig: '4d^10 5s^1',
    groupNumber: 11,
    phase: 'solid',
    firstIonizationEnergy: 731,
    halflife: '',
    meltingPoint: 961.78,
    boilingPoint: 2210,
    sublimationPoint: '',
    density20: 10.49,
    density0: '',
  },
  48: {
    number: 48,
    name: 'Cadmium',
    symbol: 'Cd',
    mass: 112.41,
    neutrons: '',
    negativity: 1.69,
    outerElectrons: 12,
    electronConfig: '4d^10 5s^2',
    groupNumber: 12,
    phase: 'solid',
    firstIonizationEnergy: 867.8,
    halflife: '',
    meltingPoint: 321.07,
    boilingPoint: 765,
    sublimationPoint: '',
    density20: '8.65 bei 25°C',
    density0: '',
  },
  49: {
    number: 49,
    name: 'Indium',
    symbol: 'In',
    mass: 114.82,
    neutrons: '',
    negativity: 1.78,
    outerElectrons: 3,
    electronConfig: '4d^10 5s^2 5p^1',
    groupNumber: 13,
    phase: 'solid',
    firstIonizationEnergy: 558.3,
    halflife: '',
    meltingPoint: 156.5985,
    boilingPoint: 2000,
    sublimationPoint: '',
    density20: 7.31,
    density0: '',
  },
  50: {
    number: 50,
    name: 'Zinn',
    symbol: 'Sn',
    mass: 118.71,
    neutrons: '',
    negativity: 1.96,
    outerElectrons: 4,
    electronConfig: '4d^10 5s^2 5p^2',
    groupNumber: 14,
    phase: 'solid',
    firstIonizationEnergy: 708.6,
    halflife: '',
    meltingPoint: 231.93,
    boilingPoint: 2620,
    sublimationPoint: '',
    density20: 'α-Zinn: 5.769, β-Zinn: 7.265',
    density0: '',
  },
  51: {
    number: 51,
    name: 'Antimon',
    symbol: 'Sb',
    mass: 121.76,
    neutrons: '',
    negativity: 2.05,
    outerElectrons: 5,
    electronConfig: '4d^10 5s^2 5p^3',
    groupNumber: 15,
    phase: 'solid',
    firstIonizationEnergy: 834,
    halflife: '',
    meltingPoint: 630.63,
    boilingPoint: 1635,
    sublimationPoint: '',
    density20: 6.697,
    density0: '',
  },
  52: {
    number: 52,
    name: 'Tellur',
    symbol: 'Te',
    mass: 127.6,
    neutrons: '',
    negativity: 2.1,
    outerElectrons: 6,
    electronConfig: '4d^10 5s^2 5p^4',
    groupNumber: 16,
    phase: 'solid',
    firstIonizationEnergy: 869.3,
    halflife: '',
    meltingPoint: 449.51,
    boilingPoint: 990,
    sublimationPoint: '',
    density20: 6.24,
    density0: '',
  },
  53: {
    number: 53,
    name: 'Iod',
    symbol: 'I',
    mass: 126.9,
    neutrons: '',
    negativity: 2.66,
    outerElectrons: 7,
    electronConfig: '4d^10 5s^2 5p^5',
    groupNumber: 17,
    phase: 'solid',
    firstIonizationEnergy: 1008.4,
    halflife: '',
    meltingPoint: 113.7,
    boilingPoint: 184,
    sublimationPoint: '',
    density20: 4.94,
    density0: '',
  },
  54: {
    number: 54,
    name: 'Xenon',
    symbol: 'Xe',
    mass: 131.29,
    neutrons: '',
    negativity: 2.6,
    outerElectrons: 8,
    electronConfig: '4d^10 5s^2 5p^6',
    groupNumber: 18,
    phase: 'gas',
    firstIonizationEnergy: 1170.4,
    halflife: '',
    meltingPoint: '−111.7',
    boilingPoint: '−108',
    sublimationPoint: '',
    density20: '',
    density0: 5.898,
  },
  55: {
    number: 55,
    name: 'Caesium',
    symbol: 'Cs',
    mass: 132.91,
    neutrons: '',
    negativity: 0.79,
    outerElectrons: 1,
    electronConfig: '6s^1',
    groupNumber: 1,
    phase: 'solid',
    firstIonizationEnergy: 375.7,
    halflife: '',
    meltingPoint: 28.44,
    boilingPoint: 690,
    sublimationPoint: '',
    density20: 1.9,
    density0: '',
  },
  56: {
    number: 56,
    name: 'Barium',
    symbol: 'Ba',
    mass: 137.33,
    neutrons: '',
    negativity: 0.89,
    outerElectrons: 2,
    electronConfig: '6s^2',
    groupNumber: 2,
    phase: 'solid',
    firstIonizationEnergy: 502.9,
    halflife: '',
    meltingPoint: 727,
    boilingPoint: 1637,
    sublimationPoint: '',
    density20: 3.62,
    density0: '',
  },
  57: {
    number: 57,
    name: 'Lanthan',
    symbol: 'La',
    mass: 138.91,
    neutrons: '',
    negativity: 1.1,
    outerElectrons: 3,
    electronConfig: '5d^1 6s^2',
    groupNumber: 3,
    phase: 'solid',
    firstIonizationEnergy: 538.1,
    halflife: '',
    meltingPoint: 920,
    boilingPoint: 3470,
    sublimationPoint: '',
    density20: 6.17,
    density0: '',
  },
  58: {
    number: 58,
    name: 'Cer',
    symbol: 'Ce',
    mass: 140.12,
    neutrons: '',
    negativity: 1.12,
    outerElectrons: 3,
    electronConfig: '4f^1 5d^1 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 534.4,
    halflife: '',
    meltingPoint: 795,
    boilingPoint: 3470,
    sublimationPoint: '',
    density20: 6.773,
    density0: '',
  },
  59: {
    number: 59,
    name: 'Praseodym',
    symbol: 'Pr',
    mass: 140.91,
    neutrons: '',
    negativity: 1.13,
    outerElectrons: 2,
    electronConfig: '4f^3 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 527,
    halflife: '',
    meltingPoint: 935,
    boilingPoint: 3130,
    sublimationPoint: '',
    density20: '6.475 bei 25°C',
    density0: '',
  },
  60: {
    number: 60,
    name: 'Neodym',
    symbol: 'Nd',
    mass: 144.24,
    neutrons: '',
    negativity: 1.14,
    outerElectrons: 2,
    electronConfig: '4f^4 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 533.1,
    halflife: '',
    meltingPoint: 1024,
    boilingPoint: 3030,
    sublimationPoint: '',
    density20: '7.003 bei 25°C',
    density0: '',
  },
  61: {
    number: 61,
    name: 'Promethium',
    symbol: 'Pm',
    mass: 146.92,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '4f^5 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 540,
    halflife: '',
    meltingPoint: 1080,
    boilingPoint: 3000,
    sublimationPoint: '',
    density20: '7.2 bei 25°C',
    density0: '',
  },
  62: {
    number: 62,
    name: 'Samarium',
    symbol: 'Sm',
    mass: 150.36,
    neutrons: '',
    negativity: 1.17,
    outerElectrons: 2,
    electronConfig: '4f^6 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 544.5,
    halflife: '',
    meltingPoint: 1072,
    boilingPoint: 1900,
    sublimationPoint: '',
    density20: '7.536 bei 25°C',
    density0: '',
  },
  63: {
    number: 63,
    name: 'Europium',
    symbol: 'Eu',
    mass: 151.9,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '4f^7 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 547.1,
    halflife: '',
    meltingPoint: 826,
    boilingPoint: 1440,
    sublimationPoint: '',
    density20: '5.245 bei 25°C',
    density0: '',
  },
  64: {
    number: 64,
    name: 'Gadolinium',
    symbol: 'Gd',
    mass: 157.25,
    neutrons: '',
    negativity: 1.2,
    outerElectrons: 3,
    electronConfig: '4f^7 5d^1 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 593.4,
    halflife: '',
    meltingPoint: 1312,
    boilingPoint: 3000,
    sublimationPoint: '',
    density20: '7.886 bei 25°C',
    density0: '',
  },
  65: {
    number: 65,
    name: 'Terbium',
    symbol: 'Tb',
    mass: 158.93,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '4f^9 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 565.8,
    halflife: '',
    meltingPoint: 1356,
    boilingPoint: 3123,
    sublimationPoint: '',
    density20: '8.253 bei 25°C',
    density0: '',
  },
  66: {
    number: 66,
    name: 'Dysprosium',
    symbol: 'Dy',
    mass: 162.5,
    neutrons: '',
    negativity: 1.22,
    outerElectrons: 2,
    electronConfig: '4f^10 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 573,
    halflife: '',
    meltingPoint: 1407,
    boilingPoint: 2600,
    sublimationPoint: '',
    density20: '8.559 bei 25°C',
    density0: '',
  },
  67: {
    number: 67,
    name: 'Holmium',
    symbol: 'Ho',
    mass: 164.93,
    neutrons: '',
    negativity: 1.23,
    outerElectrons: 2,
    electronConfig: '4f^11 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 581,
    halflife: '',
    meltingPoint: 1461,
    boilingPoint: 2600,
    sublimationPoint: '',
    density20: '8.78 bei 25°C',
    density0: '',
  },
  68: {
    number: 68,
    name: 'Erbium',
    symbol: 'Er',
    mass: 167.26,
    neutrons: '',
    negativity: 1.24,
    outerElectrons: 2,
    electronConfig: '4f^12 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 589.3,
    halflife: '',
    meltingPoint: 1529,
    boilingPoint: 2900,
    sublimationPoint: '',
    density20: '9.045 bei 25°C',
    density0: '',
  },
  69: {
    number: 69,
    name: 'Thulium',
    symbol: 'Tm',
    mass: 168.93,
    neutrons: '',
    negativity: 1.25,
    outerElectrons: 2,
    electronConfig: '4f^13 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 596.7,
    halflife: '',
    meltingPoint: 1545,
    boilingPoint: 1950,
    sublimationPoint: '',
    density20: '9.318 bei 25°C',
    density0: '',
  },
  70: {
    number: 70,
    name: 'Ytterbium',
    symbol: 'Yb',
    mass: 173.05,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '4f^14 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 603.4,
    halflife: '',
    meltingPoint: 824,
    boilingPoint: 1430,
    sublimationPoint: '',
    density20: '6.973 bei 25°C',
    density0: '',
  },
  71: {
    number: 71,
    name: 'Lutetium',
    symbol: 'Lu',
    mass: 174.97,
    neutrons: '',
    negativity: 1.27,
    outerElectrons: 3,
    electronConfig: '4f^14 5d^1 6s^2',
    groupNumber: 'La',
    phase: 'solid',
    firstIonizationEnergy: 523.5,
    halflife: '',
    meltingPoint: 1652,
    boilingPoint: 3330,
    sublimationPoint: '',
    density20: '9.84 bei 25°C',
    density0: '',
  },
  72: {
    number: 72,
    name: 'Hafnium',
    symbol: 'Hf',
    mass: 178.49,
    neutrons: '',
    negativity: 1.3,
    outerElectrons: 4,
    electronConfig: '4f^14 5d^2 6s^2',
    groupNumber: 4,
    phase: 'solid',
    firstIonizationEnergy: 658.5,
    halflife: '',
    meltingPoint: 2233,
    boilingPoint: 4603,
    sublimationPoint: '',
    density20: '13.28 bei 25°C',
    density0: '',
  },
  73: {
    number: 73,
    name: 'Tantal',
    symbol: 'Ta',
    mass: 180.95,
    neutrons: '',
    negativity: 1.5,
    outerElectrons: 5,
    electronConfig: '4f^14 5d^3 6s^2',
    groupNumber: 5,
    phase: 'solid',
    firstIonizationEnergy: 761,
    halflife: '',
    meltingPoint: 3017,
    boilingPoint: 5420,
    sublimationPoint: '',
    density20: 16.65,
    density0: '',
  },
  74: {
    number: 74,
    name: 'Wolfram',
    symbol: 'W',
    mass: 183.84,
    neutrons: '',
    negativity: 2.36,
    outerElectrons: 6,
    electronConfig: '4f^14 5d^4 6s^2',
    groupNumber: 6,
    phase: 'solid',
    firstIonizationEnergy: 770,
    halflife: '',
    meltingPoint: 3422,
    boilingPoint: 5930,
    sublimationPoint: '',
    density20: 19.25,
    density0: '',
  },
  75: {
    number: 75,
    name: 'Rhenium',
    symbol: 'Re',
    mass: 186.21,
    neutrons: '',
    negativity: 1.9,
    outerElectrons: 7,
    electronConfig: '4f^14 5d^5 6s^2',
    groupNumber: 7,
    phase: 'solid',
    firstIonizationEnergy: 760,
    halflife: '',
    meltingPoint: 3186,
    boilingPoint: 5630,
    sublimationPoint: '',
    density20: '21 bei 25°C',
    density0: '',
  },
  76: {
    number: 76,
    name: 'Osmium',
    symbol: 'Os',
    mass: 190.23,
    neutrons: '',
    negativity: 2.2,
    outerElectrons: 8,
    electronConfig: '4f^14 5d^6 6s^2',
    groupNumber: 8,
    phase: 'solid',
    firstIonizationEnergy: 840,
    halflife: '',
    meltingPoint: 3130,
    boilingPoint: 5000,
    sublimationPoint: '',
    density20: 22.59,
    density0: '',
  },
  77: {
    number: 77,
    name: 'Iridium',
    symbol: 'Ir',
    mass: 192.22,
    neutrons: '',
    negativity: 2.2,
    outerElectrons: 9,
    electronConfig: '4f^14 5d^7 6s^2',
    groupNumber: 9,
    phase: 'solid',
    firstIonizationEnergy: 880,
    halflife: '',
    meltingPoint: 2466,
    boilingPoint: 4130,
    sublimationPoint: '',
    density20: 22.56,
    density0: '',
  },
  78: {
    number: 78,
    name: 'Platin',
    symbol: 'Pt',
    mass: 195.08,
    neutrons: '',
    negativity: 2.28,
    outerElectrons: 10,
    electronConfig: '4f^14 5d^9 6s^1',
    groupNumber: 10,
    phase: 'solid',
    firstIonizationEnergy: 870,
    halflife: '',
    meltingPoint: 1768.3,
    boilingPoint: 3827,
    sublimationPoint: '',
    density20: 21.45,
    density0: '',
  },
  79: {
    number: 79,
    name: 'Gold',
    symbol: 'Au',
    mass: 196.97,
    neutrons: '',
    negativity: 2.54,
    outerElectrons: 11,
    electronConfig: '4f^14 5d^10 6s^1',
    groupNumber: 11,
    phase: 'solid',
    firstIonizationEnergy: 890.1,
    halflife: '',
    meltingPoint: 1064.18,
    boilingPoint: 2970,
    sublimationPoint: '',
    density20: 19.32,
    density0: '',
  },
  80: {
    number: 80,
    name: 'Quecksilber',
    symbol: 'Hg',
    mass: 200.59,
    neutrons: '',
    negativity: 2,
    outerElectrons: 12,
    electronConfig: '4f^14 5d^10 6s^2',
    groupNumber: 12,
    phase: 'liquid',
    firstIonizationEnergy: 1007.1,
    halflife: '',
    meltingPoint: '−38.83',
    boilingPoint: 357,
    sublimationPoint: '',
    density20: '13.5459 bei 293.15 K',
    density0: '',
  },
  81: {
    number: 81,
    name: 'Thallium',
    symbol: 'Tl',
    mass: 204.38,
    neutrons: '',
    negativity: 1.62,
    outerElectrons: 3,
    electronConfig: '4f^14 5d^10 6s^2 6p^1',
    groupNumber: 13,
    phase: 'solid',
    firstIonizationEnergy: 589.4,
    halflife: '',
    meltingPoint: 304,
    boilingPoint: 1460,
    sublimationPoint: '',
    density20: 11.85,
    density0: '',
  },
  82: {
    number: 82,
    name: 'Blei',
    symbol: 'Pb',
    mass: 207.2,
    neutrons: '',
    negativity: 2.33,
    outerElectrons: 4,
    electronConfig: '4f^14 5d^10 6s^2 6p^2',
    groupNumber: 14,
    phase: 'solid',
    firstIonizationEnergy: 715.6,
    halflife: '',
    meltingPoint: 327.43,
    boilingPoint: 1744,
    sublimationPoint: '',
    density20: 1.342,
    density0: '',
  },
  83: {
    number: 83,
    name: 'Bismut',
    symbol: 'Bi',
    mass: 208.98,
    neutrons: '',
    negativity: 2.02,
    outerElectrons: 5,
    electronConfig: '4f^14 5d^10 6s^2 6p^3',
    groupNumber: 15,
    phase: 'solid',
    firstIonizationEnergy: 703,
    halflife: '',
    meltingPoint: 271.3,
    boilingPoint: 1560,
    sublimationPoint: '',
    density20: 9.78,
    density0: '',
  },
  84: {
    number: 84,
    name: 'Polonium',
    symbol: 'Po',
    mass: 209.98,
    neutrons: '',
    negativity: 2,
    outerElectrons: 6,
    electronConfig: '4f^14 5d^10 6s^2 6p^4',
    groupNumber: 16,
    phase: 'solid',
    firstIonizationEnergy: 812.1,
    halflife: '',
    meltingPoint: 254,
    boilingPoint: 962,
    sublimationPoint: '',
    density20: 9.196,
    density0: '',
  },
  85: {
    number: 85,
    name: 'Astat',
    symbol: 'At',
    mass: 209.99,
    neutrons: '',
    negativity: 2.2,
    outerElectrons: 7,
    electronConfig: '4f^14 5d^10 6s^2 6p^5',
    groupNumber: 17,
    phase: 'solid',
    firstIonizationEnergy: 920,
    halflife: '',
    meltingPoint: 302,
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  86: {
    number: 86,
    name: 'Radon',
    symbol: 'Rn',
    mass: 222,
    neutrons: '',
    negativity: '',
    outerElectrons: 8,
    electronConfig: '4f^14 5d^10 6s^2 6p^6',
    groupNumber: 18,
    phase: 'gas',
    firstIonizationEnergy: 1037,
    halflife: '',
    meltingPoint: '−71',
    boilingPoint: '−61.8',
    sublimationPoint: '',
    density20: '',
    density0: 9.73,
  },
  87: {
    number: 87,
    name: 'Francium',
    symbol: 'Fr',
    mass: 223.02,
    neutrons: '',
    negativity: 0.7,
    outerElectrons: 1,
    electronConfig: '7s^1',
    groupNumber: 1,
    phase: 'solid',
    firstIonizationEnergy: 393,
    halflife: '',
    meltingPoint: 27,
    boilingPoint: 677,
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  88: {
    number: 88,
    name: 'Radium',
    symbol: 'Ra',
    mass: 226.03,
    neutrons: '',
    negativity: 0.9,
    outerElectrons: 2,
    electronConfig: '7s^2',
    groupNumber: 2,
    phase: 'solid',
    firstIonizationEnergy: 509.3,
    halflife: '',
    meltingPoint: 700,
    boilingPoint: 1737,
    sublimationPoint: '',
    density20: 5.5,
    density0: '',
  },
  89: {
    number: 89,
    name: 'Actinium',
    symbol: 'Ac',
    mass: 227.03,
    neutrons: '',
    negativity: 1.1,
    outerElectrons: 3,
    electronConfig: '6d^1 7s^2',
    groupNumber: 3,
    phase: 'solid',
    firstIonizationEnergy: 499,
    halflife: '',
    meltingPoint: 1050,
    boilingPoint: 3300,
    sublimationPoint: '',
    density20: 10.07,
    density0: '',
  },
  90: {
    number: 90,
    name: 'Thorium',
    symbol: 'Th',
    mass: 232.04,
    neutrons: '',
    negativity: 1.3,
    outerElectrons: 4,
    electronConfig: '6d^2 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 578,
    halflife: '',
    meltingPoint: 1755,
    boilingPoint: 4788,
    sublimationPoint: '',
    density20: 11.724,
    density0: '',
  },
  91: {
    number: 91,
    name: 'Protactinium',
    symbol: 'Pa',
    mass: 231.04,
    neutrons: '',
    negativity: 1.5,
    outerElectrons: 3,
    electronConfig: '5f^2 6d^1 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 568,
    halflife: '',
    meltingPoint: 1568,
    boilingPoint: '',
    sublimationPoint: '',
    density20: 15.37,
    density0: '',
  },
  92: {
    number: 92,
    name: 'Uran',
    symbol: 'U',
    mass: 238.03,
    neutrons: '',
    negativity: 1.38,
    outerElectrons: 3,
    electronConfig: '5f^3 6d^1 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 597.6,
    halflife: '',
    meltingPoint: 1133,
    boilingPoint: 3930,
    sublimationPoint: '',
    density20: 19.16,
    density0: '',
  },
  93: {
    number: 93,
    name: 'Neptunium',
    symbol: 'Np',
    mass: 237.05,
    neutrons: '',
    negativity: 1.36,
    outerElectrons: 3,
    electronConfig: '5f^4 6d^1 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 604.5,
    halflife: '',
    meltingPoint: 639,
    boilingPoint: 3902,
    sublimationPoint: '',
    density20: 20.45,
    density0: '',
  },
  94: {
    number: 94,
    name: 'Plutonium',
    symbol: 'Pu',
    mass: 244.06,
    neutrons: '',
    negativity: 1.28,
    outerElectrons: 2,
    electronConfig: '5f^6 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 584.7,
    halflife: '',
    meltingPoint: 639.4,
    boilingPoint: 3230,
    sublimationPoint: '',
    density20: 19.816,
    density0: '',
  },
  95: {
    number: 95,
    name: 'Americium',
    symbol: 'Am',
    mass: 243.06,
    neutrons: '',
    negativity: 1.3,
    outerElectrons: 2,
    electronConfig: '5f^7 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 578,
    halflife: '',
    meltingPoint: 1176,
    boilingPoint: 2607,
    sublimationPoint: '',
    density20: 13.67,
    density0: '',
  },
  96: {
    number: 96,
    name: 'Curium',
    symbol: 'Cm',
    mass: 247.07,
    neutrons: '',
    negativity: 1.3,
    outerElectrons: 3,
    electronConfig: '5f^7 6d^1 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 581,
    halflife: '',
    meltingPoint: 1340,
    boilingPoint: 3110,
    sublimationPoint: '',
    density20: 13.51,
    density0: '',
  },
  97: {
    number: 97,
    name: 'Berkelium',
    symbol: 'Bk',
    mass: 247,
    neutrons: '',
    negativity: 1.3,
    outerElectrons: 2,
    electronConfig: '5f^9 s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: 986,
    boilingPoint: '',
    sublimationPoint: '',
    density20: 14.78,
    density0: '',
  },
  98: {
    number: 98,
    name: 'Californium',
    symbol: 'Cf',
    mass: 251,
    neutrons: '',
    negativity: 1.3,
    outerElectrons: 2,
    electronConfig: '5f^10 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 608,
    halflife: '',
    meltingPoint: 900,
    boilingPoint: '',
    sublimationPoint: '',
    density20: 15.1,
    density0: '',
  },
  99: {
    number: 99,
    name: 'Einsteinium',
    symbol: 'Es',
    mass: 252,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '5f^11 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: 613.84,
    halflife: '',
    meltingPoint: 860,
    boilingPoint: 996,
    sublimationPoint: '',
    density20: 8.84,
    density0: '',
  },
  100: {
    number: 100,
    name: 'Fermium',
    symbol: 'Fm',
    mass: 257.1,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '5f^12 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: 852,
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  101: {
    number: 101,
    name: 'Mendelevium',
    symbol: 'Md',
    mass: 258,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '5f^13 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  102: {
    number: 102,
    name: 'Nobelium',
    symbol: 'No',
    mass: 259,
    neutrons: '',
    negativity: '',
    outerElectrons: 2,
    electronConfig: '5f^14 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  103: {
    number: 103,
    name: 'Lawrencium',
    symbol: 'Lr',
    mass: 266,
    neutrons: '',
    negativity: '',
    outerElectrons: 3,
    electronConfig: '5f^14 6d^1 7s^2',
    groupNumber: 'Ac',
    phase: 'solid',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  104: {
    number: 104,
    name: 'Rutherfordium',
    symbol: 'Rf',
    mass: 261.11,
    neutrons: '',
    negativity: '',
    outerElectrons: 4,
    electronConfig: '5f^14 6d^2 7s^2',
    groupNumber: 4,
    phase: '',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  105: {
    number: 105,
    name: 'Dubnium',
    symbol: 'Db',
    mass: 262.11,
    neutrons: '',
    negativity: '',
    outerElectrons: 5,
    electronConfig: '5f^14 6d^3 7s^2',
    groupNumber: 5,
    phase: '',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  106: {
    number: 106,
    name: 'Seaborgium',
    symbol: 'Sg',
    mass: 263.12,
    neutrons: '',
    negativity: '',
    outerElectrons: 6,
    electronConfig: '5f^14 6d^4 7s^2',
    groupNumber: 6,
    phase: '',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  107: {
    number: 107,
    name: 'Bohrium',
    symbol: 'Bh',
    mass: 262.12,
    neutrons: '',
    negativity: '',
    outerElectrons: 7,
    electronConfig: '5f^14 6d^5 7s^2',
    groupNumber: 7,
    phase: '',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
  108: {
    number: 108,
    name: 'Hassium',
    symbol: 'Hs',
    mass: 270,
    neutrons: '',
    negativity: '',
    outerElectrons: 8,
    electronConfig: '5f^14 6d^6 7s^2',
    groupNumber: 8,
    phase: '',
    firstIonizationEnergy: '',
    halflife: '',
    meltingPoint: '',
    boilingPoint: '',
    sublimationPoint: '',
    density20: '',
    density0: '',
  },
};
